export const PAGES = {
    INTRO_PAGE: "INTRO_PAGE",
    EMAIL_PAGE: "EMAIL_PAGE",
    PRE_SURVEY_PAGE: "PRE_SURVEY_PAGE",
    SURVEY_PAGE: "SURVEY_PAGE",
    FINAL_QUESTIONS_PAGE: "FINAL_QUESTIONS_PAGE",  
    THANK_YOU_PAGE: "THANK_YOU_PAGE",
}