export const GET_USER_PROGRESS_REQUEST = 'GET_USER_PROGRESS_REQUEST';
export const GET_USER_PROGRESS_SUCCESS = 'GET_USER_PROGRESS_SUCCESS'; 
export const GET_USER_PROGRESS_FAILURE = 'GET_USER_PROGRESS_FAILURE';