import React, { useState } from "react";
import "./IntroPage.css";

const IntroPage = ({ onContinue }) => {
  const [videoConfirmed, setVideoConfirmed] = useState(false);

  return (
    <div className="intro-page-container">
      <h2>Welcome to the Survey</h2>

      <section>
        <h3>What does the research involve?</h3>
        <p>
          <strong>Purpose:</strong> This study aims to evaluate and compare the
          quality of explanations generated by different AI models. Our goal is
          to help people—especially those unfamiliar with AI—recognize
          manipulated media (like deepfakes) more easily in the future.
        </p>
        <p>
          <strong>Task:</strong>{" "}
          <em>
            Please watch the short video below (under 1 minute) before
            continuing.{" "}
          </em>
        </p>
        <div className="video-wrapper">
          <iframe
            src="https://www.youtube.com/embed/dYZhRE5XBwQ"
            title="Deepfake Explanation Survey - Task"
            frameBorder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowFullScreen
          />
        </div>
        <div className="video-confirmation-wrapper">
          <input
            type="checkbox"
            id="video-confirm"
            checked={videoConfirmed}
            onChange={(e) => setVideoConfirmed(e.target.checked)}
          />
          <label htmlFor="video-confirm">
            <span className="required-asterisk">*</span> I have watched the
            video above
          </label>
        </div>
      </section>

      <section>
        <h3>Benefits</h3>
        <p>
          Your participation will help advance the creation of more inclusive
          deepfake detection tools.
        </p>
      </section>
      <section>
        <h3>Eligibility</h3>
        <p>
          You must be 18 years of age or older to fill this survey. You should
          be unfamiliar with AI based Deepfake detection tools.
        </p>
      </section>

      <section>
        <h3>Potential Risks</h3>
        <p>
          Your participation is strictly voluntary and anonymous. There are no
          major risks, only feelings of discomfort could be experienced when
          taking part in the study due to looking at the computer screen.
        </p>
      </section>

      <section>
        <h3>Withdrawing from the Study</h3>
        <p>
          You can withdraw from this study at any time while filling the form
          simply by closing this form link, but once you submit the responses,
          since they are anonymous, they can’t be removed from the database. So,
          by clicking the submit button at the end, you consent to the storage
          and use of your responses to the questionnaire for research purposes.
        </p>
      </section>

      <section>
        <h3>Confidentiality and Data Storage</h3>
        <p>
          This survey is completely anonymous. Only your responses to questions
          will be collected (in a fully anonymised format) and stored for a
          period of 5 years in Monash servers. The data collected will be kept
          confidential, under the supervision and responsibility of the Monash
          researchers, and will be used only for research purposes. After this
          period, the survey data will be deleted.
        </p>
      </section>

      <section>
        <h3>Results Dissemination</h3>
        <p>
          Only aggregated statistics will be reported in a scientific paper
          because of this study. No personally identifiable information will be
          collected or used in the publication/dissemination of the results.
        </p>
      </section>

      <section>
        <h3>Contact</h3>
        <p>
          If you have any questions about this research or your data, please
          feel free to contact any member of the research team:
        </p>
        <ul className="contact-list">
          <li>
            <strong>A/Prof. Abhinav Dhall</strong> (Chief Investigator)
            <br />
            <a href="mailto:abhinav.dhall@monash.edu">
              abhinav.dhall@monash.edu
            </a>
            <br />
            Associate Professor, Department of Data Science and AI, Monash
            University
          </li>
          <li>
            <strong>Abhijeet Narang</strong> (Student Researcher)
            <br />
            <a href="mailto:anar0033@student.monash.edu">
              anar0033@student.monash.edu
            </a>
            <br />
            Master’s Student, Monash University
          </li>
          <li>
            <strong>Parul</strong> (Student Researcher)
            <br />
            <a href="mailto:parul@monash.edu">parul@monash.edu</a>
            <br />
            PhD Student, Department of Data Science and AI, Monash University
          </li>
        </ul>
      </section>

      <button
        className="intro-continue-button"
        onClick={onContinue}
        disabled={!videoConfirmed}
      >
        I Understand and Wish to Continue
      </button>
    </div>
  );
};

export default IntroPage;

// import React from "react";
// import "./IntroPage.css";

// const IntroPage = ({ onContinue }) => {
//   return (
//     <div className="intro-page-container">
//       <div className="intro-hero">
//         <h1>Welcome to the AI Explanation Study</h1>
//         <p className="intro-subtitle">
//           Help us evaluate how people understand manipulated images.
//         </p>
//       </div>

//       <div className="intro-section">
//         <h3>📘 What does the research involve?</h3>
//         <p><strong>Purpose:</strong> This study explores how well AI-generated explanations help people recognize manipulated (deepfake) content.</p>
//         <p><strong>Task:</strong> <em>Watch the video below before continuing.</em></p>
//         <div className="video-wrapper">
//           <iframe
//             src="https://www.youtube.com/embed/YOUR_VIDEO_ID"
//             title="Survey Task Video"
//             frameBorder="0"
//             allowFullScreen
//           />
//         </div>
//         <p><strong>Benefits:</strong> Your participation will help build more inclusive and effective deepfake detection tools.</p>
//       </div>

//       <div className="intro-section">
//         <h3>✅ Eligibility</h3>
//         <p>You must be 18 or older and unfamiliar with AI-based deepfake detection tools to participate.</p>
//       </div>

//       <div className="intro-section">
//         <h3>⚠️ Potential Risks</h3>
//         <p>The only potential risk is mild discomfort from extended screen time. Participation is voluntary and anonymous.</p>
//       </div>

//       <div className="intro-section">
//         <h3>🚪 Withdrawing from the Study</h3>
//         <p>You can close the page at any time before submission. Once submitted, your anonymous responses cannot be withdrawn.</p>
//       </div>

//       <div className="intro-section">
//         <h3>🔐 Confidentiality and Data Storage</h3>
//         <p>Your anonymous responses will be securely stored on Monash University servers for 5 years and used only for research purposes.</p>
//       </div>

//       <div className="intro-section">
//         <h3>📊 Results Dissemination</h3>
//         <p>Only aggregated statistics will be published. No personal information will be collected or shared.</p>
//       </div>

//       <div className="intro-section">
//         <h3>📩 Contact</h3>
//         <p>If you have any questions, feel free to contact the research team:</p>
//         <ul className="contact-list">
//           <li>
//             <strong>A/Prof. Abhinav Dhall</strong> (Chief Investigator)<br />
//             <a href="mailto:abhinav.dhall@monash.edu">abhinav.dhall@monash.edu</a><br />
//             Associate Professor, DSAI, Monash University
//           </li>
//           <li>
//             <strong>Abhijeet Narang</strong><br />
//             <a href="mailto:anar0033@student.monash.edu">anar0033@student.monash.edu</a><br />
//             Master’s Student, Monash University
//           </li>
//           <li>
//             <strong>Parul</strong><br />
//             <a href="mailto:parul@monash.edu">parul@monash.edu</a><br />
//             PhD Student, DSAI, Monash University
//           </li>
//         </ul>
//       </div>

//       <button className="intro-continue-button" onClick={onContinue}>
//         I Understand and Wish to Continue →
//       </button>
//     </div>
//   );
// };

// export default IntroPage;
